### ISSUE TITLE
Add support for Hiera

### ISSUE THREAD

**Issue by dhoppe** [voxpupuli/puppet-caddy#31]
This module should not use a params.pp.

**Comment by alexjfisher** [comment]
Whilst the module only supports RedHat/CentOS, there's probably no point in setting up module data.  Just get rid of params.pp by moving the defaults to init.pp. This way, the reference documentation will be useful.

**Comment by dhoppe** [comment]
There was an attempt #26 to add support for Ubuntu 18.04. Keep in mind that Caddy is just a Go binary. 

I think this is a dependency for ```puppetlabs/puppet-strings``` aswell.
