### ISSUE TITLE
Support for caddy v2

### ISSUE THREAD

**Issue by shibumi** [voxpupuli/puppet-caddy#34]
Hi,
I couldn't find in your README if this project is about caddy v2 or about caddy v1. If it's about caddy v1, you should be aware, that the caddy v1 will be deprecated soon. Moreover caddy2 is a complete rewrite, so most of your configuration templates + systemd service handling will be invalid

**Comment by dhoppe** [comment]
I am pretty sure, that this module only supports Caddy v1, but we could use a fact with the version of Caddy to decide which config should be applied.

**Comment by shibumi** [comment]
@dhoppe does it even make sense to further support caddy v1? As I said: caddy v1 will be deprecated soon, it's only a matter of a few weeks since now. There will be no bugfixes for caddy v1, nor security fixes, people will be encouraged to upgrade their setup to caddy v2.

**Comment by dhoppe** [comment]
I know, but there are probably still people who use Caddy v1 and keep the .tar.gz in their own Artifactory. 

First of all, I will refactor the current code. There are some resources which should be replaced by a dedicated module and there are way too much file resources.

**Comment by kevinpetit** [comment]
Seems like there has been very few progress on Caddy v2 support - is there anything I can do to help with this?
I'm trying to get things to work in my fork, but before I put in a ton of work there, is there a plan of things on how things should be implemented?
