### ISSUE TITLE
Caddy download URL moved

### ISSUE THREAD

**Issue by AstraLuma** [voxpupuli/puppet-caddy#85]
`https://caddyserver.com/download/linux/amd64?plugins=http.git,http.filter,http.ipfilter&license=personal&telemetry=off` is a 404

The current URL is more like `https://caddyserver.com/api/download?os=linux&arch=amd64&idempotency=28527464323750`

**Comment by smortex** [comment]
Good catch, this was fixed in 4c8ebdf42d771317e814edd3bdd49729c7dc7f1e.  I removed the liked PR. Thank you for your attention!
